### ISSUE TITLE
Unknown plugin api version «1.1.0»

### ISSUE THREAD

**Issue by kainkuin** [dumkaio/paddi#1]
![image](https://user-images.githubusercontent.com/56990990/67545145-b88fc000-f700-11e9-83eb-95afbb4fcdff.png)

Good day,
I guess, since last update there is an error message appearing when plugin starts and no result — plugin is not working. The message is «Unknown plugin api version "1.1.0"»

Thank you for your work and have a good day.

---------------------------------------------------

Доброго времени суток,
Недавно (предполагаю, что после последнего обновления от 23.10.2019) при запуске плагина появляется сообщение об ошибке и плагин не работает. Содержание сообщения «Unknown plugin api version "1.1.0"». 

Спасибо за вашу работу и хорошего дня.

**Comment by otelnov** [comment]
fixed, thanks @kain-kuin
